# Generated by Django 5.1.5 on 2025-01-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
